### ISSUE TITLE
Seems to crash when I run it.

### ISSUE THREAD

**Issue by DybDan** [samherrmann/gowrap#1]
Steps I took to build it...
go get -u github.com/samherrmann/gowrap

go to source folder

go generate
go install

(I tried with go build as well.)

Target platform is linux amd64....   
I'm deveopping on ubuntu 16.10

ERROR MESSAGE:
panic: Error while getting list of supported platforms: exit status 1. Are you running at least Go version go1.7?

goroutine 1 [running]:
panic(0x55dce0, 0xc82000a9c0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/samherrmann/gowrap/gotools.init.1()
	/home/daniel/projects/gopath/src/github.com/samherrmann/gowrap/gotools/gotools.go:41 +0x11f
github.com/samherrmann/gowrap/gotools.init()
	/home/daniel/projects/gopath/src/github.com/samherrmann/gowrap/gotools/platform.go:60 +0x4f
main.init()
	/home/daniel/projects/gopath/src/github.com/samherrmann/gowrap/utils.go:16 +0x59

**Comment by DybDan** [comment]
my bad..  go version is to low on my end.
